[package]
name = "lewis-structure-solver"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
itertools = "0.14.0"
serde = {version = "1.0.228", features = ["derive"]}
serde_json = "1.0.148"
